### ISSUE TITLE
All lights are plain vanialla light color

### ISSUE THREAD

**Issue by storm37000** [CptSpaceToaster/CptsModdingLight#15]
any colored light just glows with normal vanilla light and even without optifine installed.

**Comment by CptSpaceToaster** [comment]
This is not repeatable.

This usually occurs when the transformers are sequestered, or they miss.  Check your startup logs... This mod is known to conflict with a number of mods including Optifine.  Next time you open an issue, please paste a log, and then we can discuss what actually went wrong versus wasting time in fruitless speculation.
