### ISSUE TITLE
[1.7.2] Destroying a light nerfs nearby lights

### ISSUE THREAD

**Issue by heaton84** [CptSpaceToaster/CptsModdingLight#2]
Place two different colored lights together so they mix light. Destroy one light. The remaining light does not update top the proper color, and stays mixed.

**Comment by CptSpaceToaster** [comment]
I think this was resolved about 30 commits ago... please verify that it's fixed.

**Comment by heaton84** [comment]
Yeah it's fixed. Forgot I had this open, sorry!
