### ISSUE TITLE
Crash on startup in dev environment.

### ISSUE THREAD

**Issue by xbony2** [CptSpaceToaster/CptsModdingLight#25]
Had this crash when I added this to the dev environment: https://gist.github.com/xbony2/7181f36d022c330c056d
I put in the arguments correctly, I'm pretty sure.

Not sure what I screwed up... I haven't added any integration yet, though other dependencies might have.

**Comment by xbony2** [comment]
I added ColoredLightCore_at.cfg correctly, forgot to mention that.

**Comment by CptSpaceToaster** [comment]
The dev-environment is going to change, to simply load through the CodeChickenCore (CCC)

It saves us a lot of work, by not maintaining another set of names for transformers, which I think is what broke slowly over time.  When I test, I was running gradle runClient, as my build environment can't run directly anymore either.

So... It's our fault, but I'm going to publish a more sane workaround (which involves a LOT less work for you guys as well) that basically has you install the CCC in your dev environment, and then loads a built CLC jar from there, which will handle the AT, and dependencies.

**Comment by CptSpaceToaster** [comment]
Can someone please read through those, and make sure they work?  I'd also want to know if the CLAPI is still accessible, and whether or not there are any new problems.
