### ISSUE TITLE
Odd crash report with lighting updates near the Void

### ISSUE THREAD

**Issue by xeronut** [CptSpaceToaster/CptsModdingLight#28]
http://pastebin.com/zR3XZvvF - I get this when fiddling with lighting updates around the void in Extra Utilities' Deep Dark dimension.  I got this half a dozen times either picking lava source blocks up or allowing the flowing lava to pour into the void.  I get the crash placing torches as well, at Y=3.

http://pastebin.com/LCuQ3Sc8 - I get this when doing the same thing in the Overworld.  I busted a piece of bedrock and placed a torch down.  It didn't immediately crash but when I busted the torch, crash.

http://pastebin.com/K6bDJMHq - .. and, the Nether.  Just dug straight down in Creative and let the lava flow into the void.

I wasn't sure if this was something fixed in 1.3.4 (I'm still using 1.3.3 because broken sunlight) so please disregard if useless.

**Comment by clienthax** [comment]
i think this isnt revelant any more, caused by the lighting values being larger then 0-15 for the extended data

**Comment by CptSpaceToaster** [comment]
Yeah, 1.3.3 is still quite unstable, so I'm not completely surprised.  Maybe I can spend some time here today.

**Comment by xeronut** [comment]
Update:  Similar crash for 1.3.5 build 29 - http://pastebin.com/wRR3wXqj

Dug straight down, broke bedrock, placed Red colored glowstone near the hole, no crash.  Placed lava, paused a few seconds, then crash.

**Comment by CptSpaceToaster** [comment]
A screen shot right before crash would be fantastic! (I'll look at this soon)

**Comment by xeronut** [comment]
http://imgur.com/4h5bSsQ - oops, forgot to add this to GitHub.  I tossed it and a whole gallery of pics in the MCF thread if interested.  The bedrock hole is under the flowing lava (source block is to the left).  This pic was taken maybe a second, or less, before crash.

**Comment by CptSpaceToaster** [comment]
Sounds like an issue with the lava flowing out or near the edge of a world, and then the lighting engine dies on when lava is on the edge where bedrock used to be.

**Comment by CptSpaceToaster** [comment]
That was fun!  Same issue happens on lights at the TOP of the world... presumable the far x and z extremes of the world are also unstable.....

but we can ignore those for now :)

**Comment by CptSpaceToaster** [comment]
http://coloredlightscore.us.to:8080/job/ColoredLightsCore%20v1.7.10/30/
