### ISSUE TITLE
Can't load/create world

### ISSUE THREAD

**Issue by medsal15** [CptSpaceToaster/CptsModdingLight#31]
http://pastebin.com/Az56ajVV It does the same with every versions... I just want to play with Colored Lights... :( Please tell me where is the problem (and if there is a way to fix it)

**Comment by CptSpaceToaster** [comment]
This looks like a graphics issue... What graphics card do you have in the Computer you are using?  If you are using a computer that has two, make sure Minecraft (java.exe) is using the more equipped card.

**Comment by medsal15** [comment]
How do I see which graphic I have?

**Comment by clienthax** [comment]
you are using intel grapphics to run this mod, not going to work.

**Comment by medsal15** [comment]
How do I change it (I have a portable computer)

**Comment by CptSpaceToaster** [comment]
@medsal15 Do you have any stickers describing another graphics card on your portable?  Some laptops have more than one graphics card... some don't... You'd have to look up the model of your computer, and find out if there is a second graphics card inside.  You might have a sticker on the surface advertising that you have another: 
![sticker](http://i.imgur.com/pXN4Lqm.png)

If you only have one GPU... and you're on a laptop... then there really isn't another option... the colored light core will struggle on the Intel Integrated Graphics drivers.  And it's usually not possible to add a different one.

**Comment by medsal15** [comment]
I only have one... I need a new laptop :( Thanks for the help!

**Comment by CptSpaceToaster** [comment]
Closing, due to hardware limitations.
