### ISSUE TITLE
Crash with Forge Multipart

### ISSUE THREAD

**Issue by shadowfacts** [CptSpaceToaster/CptsModdingLight#34]
When using just CLC and Forge Multipart (+ Code Chicken Lib) there is a NPE crash when I try to enter any world ([Crash Log](http://paste.cisien.com/f/278e233.txt)).

Colored Lights Core: 1.3.7.35
Code Chicken Lib: 1.1.1.110
Forge Multipart: 1.1.1.320

**Comment by CptSpaceToaster** [comment]
Hmmmmm this other crash has the same error, but different mod list:
https://gist.github.com/CptSpaceToaster/50934adfae1125b45f95

I'll rebuild with Forge 1291, and that might help a couple things... and then we can debug this further.

**Comment by shadowfacts** [comment]
In both cases it looks like something weird is happening when MC tries to generate a village. Is there anything related to villages in CLC?

**Comment by CptSpaceToaster** [comment]
No, there is no village specific code in CLC... however there are alterations to torches, and base blocks that might be included in a village...

Use this build and see if the error continues to happen: http://coloredlightscore.us.to:8080/job/ColoredLightsCore%20v1.7.10-Dev/7/artifact/build/libs/ColoredLightsCore-1.3.7.38988fc.jar

**Comment by CptSpaceToaster** [comment]
Some additional info: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445251-1-7-10-beta-wip-colored-light-progress-and?comment=1578

Another user couldn't repeat the error/conflict.

**Comment by xeronut** [comment]
Link to additional findings for this issue:  http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445251-1-7-10-beta-wip-colored-light-progress-and?comment=1585

Hope this helps.

**Comment by CptSpaceToaster** [comment]
Fixed as of https://github.com/CptSpaceToaster/CptsModdingLight/commit/f3bf803f3f65a9858b8d5b0fc376a8c0c1297821
