### ISSUE TITLE
Library to Simplify Modification

### ISSUE THREAD

**Issue by ErikMelton** [CptSpaceToaster/CptsModdingLight#37]
A friend of mine has written a library to allow easy ASM access. I highly suggest you look into it, it's very efficient and easy to use.

https://github.com/SuperSpyTX/MCLib

**Comment by CptSpaceToaster** [comment]
A wonderful cause, and a valiant effort.  It looks well done, and probably simplifies a lot of the clutter that I might have myself.

Issues: I'm not willing to go GPLv2.  So I appreciate the link to the source.  I hope I can learn a thing or two to try myself, but I don't feel comfortable bumping up the scope of my license quite yet, and forcing all subsequent users of MY end to adopt such a license.

**Comment by CptSpaceToaster** [comment]
Closing issue due to lack of discussion, reopen it if something changes, or you would like to discuss it further.
