### ISSUE TITLE
Issues rendering waypoints with VoxelMap

### ISSUE THREAD

**Issue by xeronut** [CptSpaceToaster/CptsModdingLight#42]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2261180-voxelmap-1-8-1-7-10-1-6-4-a-minimap-and-worldmap?comment=522 - link to issue information with pictures.  VoxelMap seems most affected by this issue, as seen by the pictures in the forum post.  The author of VoxelMap, MamiyaOtaru, responded a post below the one linked above with possible solutions to the problem.

A waypoint - no issues.
![img1](http://i.imgur.com/gYmb75D.png)

A waypoint with Colored Lights mod installed. Only the text is garbled - the beam itself is faint but there.
![img2](http://i.imgur.com/sDWRLo0.png)

Also, when Dynamic Lighting is enabled in the Options menu all maps render with a red overlay:
Without Colored Lights, no issue.
![img3](http://i.imgur.com/nE4Y345.png)

With Colored Lights, Minimap fullscreen and procedural maps all have red tint (untinted chunks hadn't been refreshed as I loaded the world without CLC at first).
![img4](http://i.imgur.com/dLdHj3G.png)

**Comment by xeronut** [comment]
These issues are fixed with VoxelMap release 1.5.4 - Dynamic Lighting and Waypoints function properly and I have found no issues with it outside of these.

**Comment by CptSpaceToaster** [comment]
Font is most likely borked still.

**Comment by xeronut** [comment]
The only issue I see at all with it is the color of the waypoint beacon doesn't always show.  I haven't seen issue with the font at all and I use three different texture packs (Invictus, Faithful & Sphax).  I'll do more testing - I'm sorry for closing this prematurely.

**Comment by CptSpaceToaster** [comment]
Oh cool... he must have worked around what I was doing with the font then...
