### ISSUE TITLE
opengl 1.3 compatible

### ISSUE THREAD

**Issue by jochuan** [CptSpaceToaster/CptsModdingLight#48]
colored lights core isn't compatible with opengl 1.3

**Comment by CptSpaceToaster** [comment]
You are correct, you will need a card that supports 2.1.

Now, there are some issues when GPU's that claim to be 2.1 compatible aren't, but that's mostly my bad, and a separate issue.

Let me know if you have any other questions.

**Comment by jochuan** [comment]
so you dont plan of making the mod 1.3 compatible ?

**Comment by jochuan** [comment]
please i need a reply

**Comment by CptSpaceToaster** [comment]
I do not intend on reverting to a "non-shader" based system to apply the color.  It seems to be the simplest way to achieve the result.

I have a lot to learn when it comes to OpenGL though, so at best, i can say "I don't know" and there might be something that comes up that lets me fix it for 1.3... (I don't expect that though.)

**Comment by clienthax** [comment]
can we honestly expect anyone with a card with no support for 1.3 to be able to run this decently in the first place?

**Comment by CptSpaceToaster** [comment]
I think there are a couple GPU's available that are odd edge cases that are technically sufficient.  If anything, I'd like to stick as close to vanilla MC as possible (in terms of requirements).  If Vanilla works, I want to work, but I also have to admit that my goal is a bit unrealistic.
