### ISSUE TITLE
Integer constants should be replaced with hexadecimal... 

### ISSUE THREAD

**Issue by CptSpaceToaster** [CptSpaceToaster/CptsModdingLight#5]
No seriously, things like 15728880 really need to be written as 0x0F000F0

There are several instances where a bitmask was written as an integer.  If you look in the decompiled source, that's what it gives you (and what I learned from), but it's very hard to know that 15728880 = 0000111100000000000011110000.  Instead, We can use hexadecimal and write 0x0F000F0, which makes this much more apparent.

This effects a decent amount of the lighting algorithms, and some stuff in the tessellator.

**Comment by Kizby** [comment]
Github doesn't seem to be linked up the way I would expect a sane repository to be, in that there doesn't seem to be any way to explicitly link the state of a pull request and a corresponding issue. The issue needs to be closed separately it seems (though I honestly don't know what the interface looks like for the repository owner :P)

**Comment by CptSpaceToaster** [comment]
Odd when it said "merged" I don't recall there being additional comment and close options as there are now.....

At least it connected the two when I mentioned it... That was nice.

I am an idiot at most things... This should be the end of it (and hopefully a lesson learned)
