### ISSUE TITLE
Crash upon logging into server

### ISSUE THREAD

**Issue by Lokilotus** [CptSpaceToaster/CptsModdingLight#50]
Got a crash for you- wasn't sure if it's ECL or EnderStorage causing it, but nonetheless here it is:

Crashlog with OptiFine installed (B6): http://pastebin.com/iYfHqr5t
Crashlog without OptiFine installed: http://pastebin.com/ecUReg04

This does not occur when connecting to a singleplayer world as far as I can tell, only our multiplayer server.

ECL Version: Dev build 67. Build 80 was causing some other issues on our server when I updated earlier today so I then backdated it to 67; was still an update for us though (Yay server admin). This crash was happening before however so I don't think it's an issue in this build in particular.

Forge version of the server: Latest forge as of this post.

Also of note is that I'm the only one getting the crash- none of our other players are getting it.

If there's anything else I can help with, let me know.

-Lokilotus

**Comment by CptSpaceToaster** [comment]
This is only specific to YOUR pc?

**Comment by Lokilotus** [comment]
As far as I know. Strangest thing though- we're using MultiMC for our instances, and one of our players suggested that I rebuild the instance from scratch, on the off chance it would fix things. Turns out it did. Strangely. I have no idea... I've got all the same mods and configs, yet it's suddenly working.

**Comment by CptSpaceToaster** [comment]
![suspicious](https://wayofthemoneysaver.files.wordpress.com/2010/05/suspicious-fry.jpg)

K, lets keep an eye on it.
