### ISSUE TITLE
Crash on Mojang/Forge loading screen

### ISSUE THREAD

**Issue by Diserasta** [CptSpaceToaster/CptsModdingLight#51]
As per page 89 of the official forum thread (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445251-1-7-10-beta-wip-colored-light-progress-and?comment=1775), the current version of the ColouredLightCore does not agree with forge's loading screen. 
http://pastebin.com/EmLnaQQC
Something to do with the font renderer perchance?
You probably already know about this, but better to make sure.

**Comment by CptSpaceToaster** [comment]
TY for the report... It's known, but there wasn't an issue tracking it here.
