### ISSUE TITLE
Light remains even when breaking blocks

### ISSUE THREAD

**Issue by JBYoshi** [CptSpaceToaster/CptsModdingLight#54]
Steps to reproduce:
1. Go into a dark place.
2. Place a colored light block (I used a redstone torch).
3. Break the block.

**Comment by CptSpaceToaster** [comment]
Other related issues have been noticed:

https://github.com/CptSpaceToaster/CptsModdingLight/issues/41
https://github.com/CptSpaceToaster/CptsModdingLight/issues/39
