### ISSUE TITLE
Transparent blocks (world)

### ISSUE THREAD

**Issue by fireblade51** [CptSpaceToaster/CptsModdingLight#57]
When I install Coloredlightcore, all my blocks become transparent. I really want to use that mod, but it doesn't work :(

![2015-12-03_12 24 10](https://cloud.githubusercontent.com/assets/6614093/11568216/f453b104-99b8-11e5-9f43-c0fb3b1fa8b5.png)
There's a way to fix that?

**Comment by CptSpaceToaster** [comment]
Certain blocks don't render from other mods.  Optifine can get in the way.

Only load forge and CLC together, and see what becomes of it.

**Comment by fireblade51** [comment]
I have this issue now
![2015-12-03_13 04 33](https://cloud.githubusercontent.com/assets/6614093/11569190/8c9cfb78-99be-11e5-8905-30eb94b0ffe3.png)

**Comment by CptSpaceToaster** [comment]
Forge version?

**Comment by fireblade51** [comment]
I use Forge 1.7.10 - 10.13.4.1558 now for an other test whit the same issue, but in this picture I use Forge 1.7.10 - 10.13.2.1300

**Comment by CptSpaceToaster** [comment]
I think the last version that I tested it against was 1338.  Try that, and if it doesn't work for you, then it might be a graphics driver issue.  CLC bumped up the requirements when rendering and uses shaders (more so than what Minecraft does normally at least) which need to be supported by your GPU.  

Make sure you're using a graphics adapter that fully supports OpenGL 2.1.  Some desktops/laptops have a weaker Intel based card on their motherboard, and a dedicated GPU that may not be used.  (Check your Nvidia/ATI control panel to see if the right GPU is trying to handle instances of java.exe/minecraft)

If you don't have a dedicated GPU, then you might not be able to run the mod in it's current state.  I wouldn't be surprised if our implementation wasn't correct in every case, but I'm not in active development.

Sorry.

**Comment by fireblade51** [comment]
okay I will check it later, thank you for your quick response and good luck for this incredible mod. :)
