### ISSUE TITLE
[Question] Setup still works?

### ISSUE THREAD

**Issue by ghost** [CptSpaceToaster/CptsModdingLight#59]
I recently had a computer that got corrupted that contained this mod already setup and working in eclipse with some modifications. I went to re-download the src from this but now the gradle is producing errors with a build fail with the 1.7.10 or when setup with eclipse crashes instantly do to no-method errors for the ones that do have the gradle working. The 1.7.2 seems to be the only one that can run with the setups. Was there any changes in the code since December that are not showing?

**Comment by CptSpaceToaster** [comment]
I am unsure.  I'm not hosting the source personally anymore... so it won't be available as a maven dependency.  Outside of that... I'm fairly removed from the forge build environment to really know how to help debug your issues.  Sorry about that.

The last [commit](https://github.com/CptSpaceToaster/CptsModdingLight/commits/1.7.10) was Jul 16, 2015

That's all I got....

**Comment by ghost** [comment]
Ok then at least the 1.7.2 works then might be with how I have the forge installed or something. Hopefully it can be fixed or I may just use the 1.7.2 as the starting point. Thank you anyway.
